xcopy /v /y /i "%~dp0\..\API\bin\cacert.pem" "%~dp0\Output\driver\massless\bin\win64"
xcopy /v /y /i "%~dp0\..\API\bin\eCAMFwSw.dll" "%~dp0\Output\driver\massless\bin\win64"
xcopy /v /y /i "%~dp0\..\API\bin\MasslessPen.dll" "%~dp0\Output\driver\massless\bin\win64"
xcopy /v /y /i "%~dp0\..\API\bin\opencv_world341.dll" "%~dp0\Output\driver\massless\bin\win64"
:: xcopy /v /y /i "%~dp0\..\API\bin\zlib1.dll" "%~dp0\Output\driver\massless\bin\win64"
